# Generated by Django 5.2.3 on 2025-06-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_receipe_created_at_historicalreceipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreceipe',
            name='receipe_view_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='receipe',
            name='receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
