# Generated by Django 5.2.3 on 2025-06-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trancelaionApp', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
