# Generated by Django 5.2.3 on 2025-08-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvread', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='emil',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
    ]
