# Generated by Django 5.2.3 on 2025-06-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_receipe_created_at_historicalreceipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreceipe',
            name='receipe_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipes'),
        ),
    ]
