# Generated by Django 5.2.3 on 2025-06-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_alter_historicalreceipe_receipe_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreceipe',
            name='recipe_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='receipe',
            name='recipe_count',
            field=models.IntegerField(default=1),
        ),
    ]
