# Generated by Django 5.2.3 on 2025-06-26 14:30

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_todo_delete_cars_delete_product_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='creatd_at',
        ),
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5bb5138d-5c96-417c-a0e4-bf94af07233e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
