# Generated by Django 5.2.3 on 2025-06-26 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_todo_creatd_at_todo_created_at_alter_todo_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ca8b6d04-ddfb-4c6c-9f0a-b1ba0ccf2975'), editable=False, primary_key=True, serialize=False),
        ),
    ]
