# Generated by Django 5.2.3 on 2025-06-26 14:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('48d393ce-cf47-4a99-b0b1-a90c05112845'), editable=False, primary_key=True, serialize=False),
        ),
    ]
