# Generated by Django 5.2.3 on 2025-06-27 13:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f48e385a-40ae-4b68-a775-fa13917bfed5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
