# Generated by Django 5.2.3 on 2025-06-27 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c625da40-655d-4b10-becc-a1d140b61cfd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
