# Generated by Django 5.2.3 on 2025-06-29 13:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5c5f7c09-8643-4547-be4a-b6a60fc03f76'), editable=False, primary_key=True, serialize=False),
        ),
    ]
