# Generated by Django 5.2.3 on 2025-06-29 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f0500015-55df-43ec-9492-80909b48bcaa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
