# Generated by Django 5.2.3 on 2025-08-02 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3b45747b-de0d-412d-8252-e117ef4fa37f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
