# Generated by Django 5.2.3 on 2025-08-02 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('48056d2c-d8ef-45fd-b332-303dadfa3c56'), editable=False, primary_key=True, serialize=False),
        ),
    ]
