# Generated by Django 5.2.3 on 2025-08-02 17:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7d357cb5-902d-485d-87fa-8fc3b06f8a63'), editable=False, primary_key=True, serialize=False),
        ),
    ]
