# Generated by Django 5.2.3 on 2025-08-03 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('411bd92a-8235-428d-ba13-995ddb86cb59'), editable=False, primary_key=True, serialize=False),
        ),
    ]
