# Generated by Django 5.2.3 on 2025-08-03 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d3736560-6515-4cbc-bbf4-1acf8700423b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
