# Generated by Django 5.2.3 on 2025-08-03 15:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a11e50ce-a3e4-4c4a-b026-c7809c035232'), editable=False, primary_key=True, serialize=False),
        ),
    ]
