# Generated by Django 5.2.3 on 2025-06-26 14:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('07ba7c9b-2621-4f3a-8a7d-1a5a37a705c1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
