# Generated by Django 5.2.3 on 2025-06-28 06:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9df7e804-6722-4d5d-9c9a-bc5864b60293'), editable=False, primary_key=True, serialize=False),
        ),
    ]
